language: R
warnings_are_errors: true
r_check_args: --as-cran --run-dontrun
r_packages:
   - covr
r_github_packages:
   - fmichonneau/rncl
after_success:
   - Rscript -e 'library(covr); package_coverage(function_exclusions="print\\."); package_coverage(function_exclusions="factory$"); codecov(); '
notifications:
  slack:
    secure: chYOxbPBFVAMbDbNc/6tDn5749/qOfJkM+hfTraG9LGstCZC2C4I7rxb3BRkUHphIbFuQiH8BW/L+BKPXkLBL8Hrz4uMMyD3RtMX1A9fZ9WizkHMT4GLCHE011TITiYIeJvv41R7RBuy6rn3RLpID5KeMTTDphIz1TOZdl1zsxqds=
